halo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('qa.urls', namespace='qa')),
]

qa/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'qa'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('new_question/', views.create_question, name='new_question'),
    path('<slug:question>/', views.question_detail, name='question_detail'),
    path('tag/<slug:tag_slug>', views.home, name="question_by_tag"),
    path('user/vote/', views.voting, name='vote'),
]

qa/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import IntegrityError
from taggit.managers import TaggableManager
# Create your models here.


class Question(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='created')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="question")
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    votes = models.IntegerField(default=0)
    tags = TaggableManager()

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # Send argument to question_detail route
        return reverse('qa:question_detail', args=[self.slug])

    def upvote(self, user):
        try:
            self.question_vote.create(user=user, question=self, vote_type='up')
            self.votes += 1
            self.save(update_fields=['votes'])
        except IntegrityError:
            return "Already upvotes"
        return 'ok'

    def downvote(self, user):
        try:
            self.question_vote.create(
                user=user, question=self, vote_type='down')
            self.votes -= 1
            self.save(update_fields=['votes'])
        except IntegrityError:
            return "Already downvotes"
        return 'ok'


class Answer(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="answers")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="answer")
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    votes = models.IntegerField(default=0)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.question}'

    def upvote(self, user):
        try:
            self.answer_vote.create(user=user, answer=self, vote_type='up')
            self.votes += 1
            self.save(update_fields=['votes'])
        except IntegrityError:
            return "Already upvotes"
        return 'ok'
    
    def downvote(self, user):
        try:
            self.answer_vote.create(user=user, answer=self, vote_type='down')
            self.votes -= 1
            self.save(update_fields=['votes'])
        except IntegrityError:
            return "Already downvotes"
        return 'ok'
    
class UserVoteQuestion(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_vote_question')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='question_vote')
    vote_type = models.CharField(max_length=10)

    class Meta:
        unique_together = ('user', 'question', 'vote_type')


class UserVoteAnswer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_vote_answer')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='answer_vote')
    vote_type = models.CharField(max_length=10)

    class Meta:
        unique_together = ('user', 'answer', 'vote_type')

qa/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Answer, Question
from taggit.models import Tag


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
        help_texts = {
            'username': None,
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password don\'t match')
        return cd['password2']


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('body',)
        labels = {
            'body': ""
        }
        
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'body', 'tags')
        labels = {
            'body': 'Content'
        }

class SearchForm(forms.Form):
    query = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Enter Keywords'}))
    

qa/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm, AnswerForm, QuestionForm, SearchForm
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Question, Answer
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from halo.common.decorators import ajax_required
from django.utils.text import slugify


# Create your views here.
def home(request, tag_slug=None):
    search_form = SearchForm()
    user_count = User.objects.count()
    object_list = Question.objects.all()

    # Handle tag filter
    tag = None 
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    # Handle search function
    if 'query' in request.GET:
        search_form = SearchForm(request.GET)
        if search_form.is_valid():
            query = search_form.cleaned_data['query']
            object_list = Question.objects.filter(title__contains=query)

    paginator = Paginator(object_list, 5) # 5 questions each page
    page = request.GET.get('page')
    try: 
        questions = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        questions = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        questions = paginator.page(paginator.num_pages)

    return render(request, 'extends/home.html', {'user_count': user_count, 'question_count': Question.objects.count() ,'page': page, 'questions': questions, 'tag': tag, 'search_form': search_form})



def question_detail(request, question):
    # Render question detail view
    user_count = User.objects.count()
    question = get_object_or_404(Question, slug=question)
    search_form = SearchForm()
    # List of active answers for this post
    answers = question.answers.all()

    new_answer = None

    # Handle user's answer
    if request.method == "POST":
        answer_form = AnswerForm(request.POST)
        if answer_form.is_valid():
            # Create Answer object but don't save to database yet
            new_answer = answer_form.save(commit=False)
            # Assign the current question to the answer
            new_answer.question = question
            # Assign user to the answer
            new_answer.user = get_object_or_404(User, username=request.user.username)
            # Save the answer to the database
            new_answer.save()
    else:
        answer_form = AnswerForm()

    return render(request, 'extends/detail.html', {'question': question, 'user_count': user_count, 'question_count': Question.objects.count(), 'answers': answers, 'new_answer': new_answer, 'answer_form': answer_form, 'search_form': search_form})


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but not saving it yet
            new_user = user_form.save(commit=False)
            # Set the choosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'user_form': user_form})


@login_required
def create_question(request):
    user = get_object_or_404(User, username=request.user.username)
    new_question = None
    if request.method == "POST":
        question_form = QuestionForm(request.POST)
        if question_form.is_valid():
            new_question = question_form.save(commit=False)
            new_question.slug = slugify(new_question.title)
            new_question.user = user 
            new_question.save()
            for tag in question_form.cleaned_data['tags']:
                new_question.tags.add(tag.lower())
    else:
        question_form = QuestionForm()
    return render(request, 'extends/question.html', {'question_form': question_form, 'user_count': User.objects.count(), 'question_count': Question.objects.count(), 'new_question': new_question})


@ajax_required
@require_POST
@login_required
def voting(request):
    data = request.POST
    if data['action'] == 'upvote':
        if data['qa'] == 'q':
            user = get_object_or_404(User, id=data['id'])
            question = get_object_or_404(Question, slug=data['identity'])
            res = question.upvote(user)
        else: 
            user = get_object_or_404(User, id=data['id'])
            answer = get_object_or_404(Answer, id=data['identity'])
            res = answer.upvote(user)
    else:
        if data['qa'] == 'q':
            user = get_object_or_404(User, id=data['id'])
            question = get_object_or_404(Question, slug=data['identity'])
            res = question.downvote(user)
        else: 
            user = get_object_or_404(User, id=data['id'])
            answer = get_object_or_404(Answer, id=data['identity'])
            res = answer.downvote(user)
   
    return JsonResponse({'status': res})
 

qa/templates/base.html
{% load static %}
{% load taggit_templatetags2_tags %}
{% get_taglist as tags for 'qa.Question' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href='https://use.fontawesome.com/releases/v5.1.0/css/all.css'>
    <title>QA</title>
</head>

<body>
    <header id='header'>
        <div class="logo-img">
            <a href="{% url 'qa:home' %}">
                <img src="{% static 'img/logo.png' %}" alt="logo">
            </a>
        </div>
        <div class="search-bar">
            <form method="get" action="{% url 'qa:home' %}">
                {{search_form.as_p}}
                {% csrf_token %}
            </form>
            <i class="fas fa-search"></i>
        </div>
        <div class="navigation">
            <ul>
                {% if request.user.is_authenticated %}
                <li style="color: #15A4FA">Hello {{request.user.first_name}}</li>
                <li><a href="{% url 'qa:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'qa:login' %}">Login</a></li>
                <li><a href="{% url 'qa:register' %}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </header>

    <section id="main-content">
        <aside id="left-sidebar">
            <ul>
                <li class="btn">
                    <a href="{% url 'qa:new_question' %}"><button class="ask-question"><i class="fas fa-plus"></i> ASK A QUESTION</button></a>
                </li>
                <h3 class="my-1">Tags:</h3>
                <li class="tags">
                    {% for tag in tags %}
                    <a class="tag" href="{% url 'qa:question_by_tag' tag.slug %}">{{tag}}</a>
                    {%endfor%}
                </li>
            </ul>
        </aside>
        <div class="content">
            {%block content%} {%endblock%}
        </div>
        <aside id="right-sidebar">
            <div class="statistic">
                <ul>
                    <li class="question-count">
                        <p>Questions</p>
                        <p><span>{{question_count}}</span></p>
                    </li>
                    <li class="member-count">
                        <p>Members</p>
                        <p><span>{{user_count}}</span></p>
                    </li>
                </ul>
            </div>
            <div class="most-used-tags">
                <h4>MOST USED TAG</h4>
                <ul class="tags">
                        {% for tag in tags %}
                        <li>
                            <a class="tag" href="{% url 'qa:question_by_tag' tag.slug %}">{{tag}}</a> x {{tag.num_times}}
                        </li>
                        {% endfor %}
                </ul>
            </div>
        </aside>
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/
jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/
js.cookie.min.js"></script>
    <script>
        var csrftoken = Cookies.get('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $(document).ready(function () {
            {% block domready %}
            {% endblock %}
        });
        {% block script %} {% endblock %}
    </script>
    
</body>

</html>

qa/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>