halo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('qa.urls', namespace='qa')),
]

qa/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'qa'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('new_question/', views.create_question, name='new_question'),
    path('<slug:question>/', views.question_detail, name='question_detail'),
    path('tag/<slug:tag_slug>', views.home, name="question_by_tag"),
    path('user/vote/', views.voting, name='vote'),
]

qa/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import IntegrityError
from taggit.managers import TaggableManager
# Create your models here.


class Question(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='created')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="question")
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    votes = models.IntegerField(default=0)
    tags = TaggableManager()

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # Send argument to question_detail route
        return reverse('qa:question_detail', args=[self.slug])

    def upvote(self, user):
        try:
            self.question_vote.create(user=user, question=self, vote_type='up')
            self.votes += 1
            self.save(update_fields=['votes'])
        except IntegrityError:
            return "Already upvotes"
        return 'ok'

    def downvote(self, user):
        try:
            self.question_vote.create(
                user=user, question=self, vote_type='down')
            self.votes -= 1
            self.save(update_fields=['votes'])
        except IntegrityError:
            return "Already downvotes"
        return 'ok'


class Answer(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="answers")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="answer")
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    votes = models.IntegerField(default=0)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.question}'

    def upvote(self, user):
        try:
            self.answer_vote.create(user=user, answer=self, vote_type='up')
            self.votes += 1
            self.save(update_fields=['votes'])
        except IntegrityError:
            return "Already upvotes"
        return 'ok'
    
    def downvote(self, user):
        try:
            self.answer_vote.create(user=user, answer=self, vote_type='down')
            self.votes -= 1
            self.save(update_fields=['votes'])
        except IntegrityError:
            return "Already downvotes"
        return 'ok'
    
class UserVoteQuestion(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_vote_question')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='question_vote')
    vote_type = models.CharField(max_length=10)

    class Meta:
        unique_together = ('user', 'question', 'vote_type')


class UserVoteAnswer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_vote_answer')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='answer_vote')
    vote_type = models.CharField(max_length=10)

    class Meta:
        unique_together = ('user', 'answer', 'vote_type')

qa/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Answer, Question
from taggit.models import Tag


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
        help_texts = {
            'username': None,
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password don\'t match')
        return cd['password2']


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('body',)
        labels = {
            'body': ""
        }
        
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'body', 'tags')
        labels = {
            'body': 'Content'
        }

class SearchForm(forms.Form):
    query = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Enter Keywords'}))
    

qa/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm, AnswerForm, QuestionForm, SearchForm
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Question, Answer
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from halo.common.decorators import ajax_required
from django.utils.text import slugify


# Create your views here.
def home(request, tag_slug=None):
    search_form = SearchForm()
    user_count = User.objects.count()
    object_list = Question.objects.all()

    # Handle tag filter
    tag = None 
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    # Handle search function
    if 'query' in request.GET:
        search_form = SearchForm(request.GET)
        if search_form.is_valid():
            query = search_form.cleaned_data['query']
            object_list = Question.objects.filter(title__contains=query)

    paginator = Paginator(object_list, 5) # 5 questions each page
    page = request.GET.get('page')
    try: 
        questions = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        questions = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        questions = paginator.page(paginator.num_pages)

    return render(request, 'extends/home.html', {'user_count': user_count, 'question_count': Question.objects.count() ,'page': page, 'questions': questions, 'tag': tag, 'search_form': search_form})



def question_detail(request, question):
    # Render question detail view
    user_count = User.objects.count()
    question = get_object_or_404(Question, slug=question)
    search_form = SearchForm()
    # List of active answers for this post
    answers = question.answers.all()

    new_answer = None

    # Handle user's answer
    if request.method == "POST":
        answer_form = AnswerForm(request.POST)
        if answer_form.is_valid():
            # Create Answer object but don't save to database yet
            new_answer = answer_form.save(commit=False)
            # Assign the current question to the answer
            new_answer.question = question
            # Assign user to the answer
            new_answer.user = get_object_or_404(User, username=request.user.username)
            # Save the answer to the database
            new_answer.save()
    else:
        answer_form = AnswerForm()

    return render(request, 'extends/detail.html', {'question': question, 'user_count': user_count, 'question_count': Question.objects.count(), 'answers': answers, 'new_answer': new_answer, 'answer_form': answer_form, 'search_form': search_form})


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but not saving it yet
            new_user = user_form.save(commit=False)
            # Set the choosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'user_form': user_form})


@login_required
def create_question(request):
    user = get_object_or_404(User, username=request.user.username)
    new_question = None
    if request.method == "POST":
        question_form = QuestionForm(request.POST)
        if question_form.is_valid():
            new_question = question_form.save(commit=False)
            new_question.slug = slugify(new_question.title)
            new_question.user = user 
            new_question.save()
            for tag in question_form.cleaned_data['tags']:
                new_question.tags.add(tag.lower())
    else:
        question_form = QuestionForm()
    return render(request, 'extends/question.html', {'question_form': question_form, 'user_count': User.objects.count(), 'question_count': Question.objects.count(), 'new_question': new_question})


@ajax_required
@require_POST
@login_required
def voting(request):
    data = request.POST
    if data['action'] == 'upvote':
        if data['qa'] == 'q':
            user = get_object_or_404(User, id=data['id'])
            question = get_object_or_404(Question, slug=data['identity'])
            res = question.upvote(user)
        else: 
            user = get_object_or_404(User, id=data['id'])
            answer = get_object_or_404(Answer, id=data['identity'])
            res = answer.upvote(user)
    else:
        if data['qa'] == 'q':
            user = get_object_or_404(User, id=data['id'])
            question = get_object_or_404(Question, slug=data['identity'])
            res = question.downvote(user)
        else: 
            user = get_object_or_404(User, id=data['id'])
            answer = get_object_or_404(Answer, id=data['identity'])
            res = answer.downvote(user)
   
    return JsonResponse({'status': res})
 

qa/templates/extends/detail.html
{% extends "../base.html" %}

{% block content %}
<!-- Question detail -->
<div class="container">
    <div class="question-detail">
        <div class="votes-count">
            <a href="" class="popup"><span class="upvote" data-id="{{user.id}}" data-qa="q" data-identity="{{question.slug}}" data-action="upvote"><i class="fas fa-sort-up"></i></span></a>
            {{question.votes}}
            <a href="" class="popup"><span class="downvote" data-id="{{user.id}}" data-qa="q" data-identity="{{question.slug}}" data-action="downvote"><i class="fas fa-sort-down"></i></span></a>
        </div>
        <div class="question-content">
            <p class="question-title py-1">
                {{ question.title }}
                {% for tag in question.tags.all %}
                <a href="{% url 'qa:question_by_tag' tag.slug %}" class="tag">{{tag.name}}</a>
                {% endfor %}
            </p>
            <p class="date">Asked by {{question.user.username}} at {{question.created}}</p>
            <p class="question-body py-1">{{ question.body }}</p>
        </div>
    </div>

    <!-- Render number of total answers and answers-->
    <div class="answers-block">
        {% with answers.count as total_answers %}
        <h4 class="py-1">{{total_answers}} answer{{total_answers|pluralize}}</h4>
        {% endwith %}
        <div class="answers my-1">
            {% for answer in answers %}
            <div class="answer-detail my-2">
                <div class="votes-count">
                    <a href="" class="popup"><span class="upvote" data-id="{{user.id}}" data-qa="a" data-identity="{{answer.id}}" data-action="upvote"><i class="fas fa-sort-up"></i></span></a>
                    {{answer.votes}}
                    <a href="" class="popup"><span class="downvote" data-id="{{user.id}}" data-qa="a" data-identity="{{answer.id}}" data-action="downvote"><i class="fas fa-sort-down"></i></span></a>
                </div>
                <div class="answer-content">
                    <p class="answer-body">
                        {{answer.body}}
                    </p>
                    <p class="date my-2">Answered on {{answer.created}} by {{answer.user.username}}</p>
                </div>
            </div>
            <hr>
            {% empty %}
            <p>There is no answer yet</p>
            {% endfor %}
            
        </div>
    </div>

    <!-- Render answer form, if user has answered, notify them that answer has been added -->
    {% if new_answer %}
        <h2>Your answer has been added</h2>
    {% else %}
        {% if request.user.is_authenticated %}
            <h2 class="my-1">Add a new answer</h2>
            <form action="" method="post" class="answer-form">
                {{answer_form.as_p}}
                {% csrf_token %}
                <p class="my-1"><input type="submit" value="Add answer"></p>
            </form>
        {% else %}
            <p>Please login to answer</p>
        {% endif %}
    {% endif %}
</div>

{% endblock %}

{% block script %}
    {%block domready %}
        $('span.upvote, span.downvote').off().click(function(e) {
            e.preventDefault()
            $.ajax({
                url: "{% url 'qa:vote' %}",
                type: "post",
                data: {id: $(this).data('id'), qa: $(this).data('qa'), identity: $(this).data('identity'),
                action: $(this).data('action')},
                dataType: "json",
                success: function(data){
                    let status = data['status']
                    popUpFunction(e.target.parentNode, status)
                },
                error: function(){
                    popUpFunction(e.target.parentNode, 'login')
                }
            })
        })

    {% endblock %}
    function popUpFunction(element, status){
        <!-- Get vote element -->
        let vote = element;
    
        <!-- Create span text to notify user -->
        let popuptext = document.createElement('span')
        <!-- Create attributes and set it into span element -->
        let class_ = document.createAttribute('class')
        class_.value = "popuptext"
        let id_ = document.createAttribute('id')
        id_.value = "myPopup"
        popuptext.setAttributeNode(class_)
        popuptext.setAttributeNode(id_)

        <!-- Notify text to user -->
        if (status === 'ok'){
            popuptext.textContent = "Thanks you for voting!"
        } else if (status === 'Already upvotes'){
            popuptext.textContent = "You've already voted :)"
        } else {
            popuptext.innerHTML = "Please login to votes!"
        }
        popuptext.classList.toggle("show");

        <!-- Append span to vote  -->
        vote.appendChild(popuptext)

        <!-- Remove Child and reload after 2s -->
        setTimeout(function() {
            vote.removeChild(popuptext);
            location.reload();
        }, 2000)
    }
{% endblock %}

qa/templates/extends/home.html
{% extends '../base.html' %}

{% block content %}
<!-- All questions -->
<p class="content-title">All Questions</p>
<div class="questions">
    {% for question in questions %}
    <div class="question">
        <div class="question-content">
            <a  href="{{question.get_absolute_url}}"><h4>{{question.title}}</h4></a>
            <p class="my-2">{{question.body|truncatewords:30}}</p>
            {% for tag in question.tags.all %}
            <a href="{% url 'qa:question_by_tag' tag.slug %}" class="tag">{{tag.name}}</a>
            {%endfor%}
        </div>
        <div class="informations">
            <p><span>{{question.votes}}</span> vote{{question.votes|pluralize}}</p>
            <p><span style="background-color: #1ABC9C !important; color: #fff;">{{question.answers.count}}</span> answer{{question.answers.count|pluralize}}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% include "../pagination.html" with page=questions %}
{% endblock %}

qa/templates/extends/question.html
{% extends '../base.html' %}

{% block content %}
<!-- Render "create question" form, if user has created question, notify them -->
{% if new_question %}
    <h2>Your question has been created! Go back to <a href="{% url 'qa:home' %}">homepage</a></h2>
{%else%}
<div class="container">
    <h2>Create a new question</h2>
    <form action="" method="post">
        {{question_form.as_p}}
        {% csrf_token %}
        <p class="my-1"><input type="submit" value="Create question"></p>
    </form>
</div>
{%endif%}
{% endblock %}